# Generated by Django 4.1.1 on 2023-07-10 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UploadImage',
        ),
    ]
