# Generated by Django 4.1.1 on 2023-07-10 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='upload_date',
        ),
        migrations.AddField(
            model_name='uploadimage',
            name='thumb',
            field=models.ImageField(default=0, upload_to='thumbs'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
