# Generated by Django 4.1.1 on 2023-07-10 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0002_remove_uploadimage_upload_date_uploadimage_thumb_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadimage',
            name='caption',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to='images'),
        ),
    ]
