# Generated by Django 4.1.1 on 2023-07-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tools', '0003_uploadimage_caption_alter_uploadimage_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='uploadimage',
            name='caption',
        ),
        migrations.AlterField(
            model_name='uploadimage',
            name='image',
            field=models.ImageField(upload_to='image'),
        ),
    ]
